version: '3.8'
services:
  frontend:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/web/media:/data/web/media 
    ports:
      - "8443:443"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - django
    networks:
      - app-network

  django:
    container_name: django
    hostname: django
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    user: "${UID}:${GID}"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    networks:
      - app-network

  psql:
    container_name: psql
    image: postgis/postgis:15-3.3
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge