# Dockerfile.nginx
FROM nginx:latest

RUN mkdir -p /etc/nginx/ssl

ARG COUNTRY_NAME
ARG STATE_NAME
ARG LOCALITY_NAME
ARG ORGANIZATION_NAME
ARG ORGANIZATIONAL_UNIT
ARG COMMON_NAME
ARG UNIQUE_ID

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/fullchain.pem -keyout /etc/nginx/ssl/privkey.pem -subj "/C=${COUNTRY_NAME}/ST=${STATE_NAME}/L=${LOCALITY_NAME}/O=${ORGANIZATION_NAME}/OU=${ORGANIZATIONAL_UNIT}/CN=${COMMON_NAME}/UID=${UNIQUE_ID}"

COPY nginx.conf /etc/nginx/nginx.conf